// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phonebook.proto

package crud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	_ "github.com/mwitkow/go-proto-validators"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactFieldNum int32

const (
	ContactFieldNum_C_ID    ContactFieldNum = 0
	ContactFieldNum_C_NAME  ContactFieldNum = 1
	ContactFieldNum_C_PHONE ContactFieldNum = 2
)

var ContactFieldNum_name = map[int32]string{
	0: "C_ID",
	1: "C_NAME",
	2: "C_PHONE",
}

var ContactFieldNum_value = map[string]int32{
	"C_ID":    0,
	"C_NAME":  1,
	"C_PHONE": 2,
}

func (x ContactFieldNum) String() string {
	return proto.EnumName(ContactFieldNum_name, int32(x))
}

func (ContactFieldNum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{0}
}

type Contact struct {
	// id записи
	Id *wrappers.Int64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// имя
	Name *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// телефон
	Phone                *wrappers.StringValue `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() *wrappers.Int64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contact) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Contact) GetPhone() *wrappers.StringValue {
	if m != nil {
		return m.Phone
	}
	return nil
}

type ListContactsRequest struct {
	// фильтры для отбора записей
	Filter *ListContactFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// список названий полей, которые возвращать в ответе. Deprecated - не успел)
	ReturnedFields []ContactFieldNum `protobuf:"varint,2,rep,packed,name=returnedFields,proto3,enum=api.crud.ContactFieldNum" json:"returnedFields,omitempty"` // Deprecated: Do not use.
	// ограничение числа возвращаемых записей
	Limit                *wrappers.Int32Value `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListContactsRequest) Reset()         { *m = ListContactsRequest{} }
func (m *ListContactsRequest) String() string { return proto.CompactTextString(m) }
func (*ListContactsRequest) ProtoMessage()    {}
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{1}
}

func (m *ListContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsRequest.Unmarshal(m, b)
}
func (m *ListContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsRequest.Marshal(b, m, deterministic)
}
func (m *ListContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsRequest.Merge(m, src)
}
func (m *ListContactsRequest) XXX_Size() int {
	return xxx_messageInfo_ListContactsRequest.Size(m)
}
func (m *ListContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsRequest proto.InternalMessageInfo

func (m *ListContactsRequest) GetFilter() *ListContactFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

// Deprecated: Do not use.
func (m *ListContactsRequest) GetReturnedFields() []ContactFieldNum {
	if m != nil {
		return m.ReturnedFields
	}
	return nil
}

func (m *ListContactsRequest) GetLimit() *wrappers.Int32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

type ListContactFilter struct {
	// список id
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	// список имен
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// список телефонов
	Phones               []string `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListContactFilter) Reset()         { *m = ListContactFilter{} }
func (m *ListContactFilter) String() string { return proto.CompactTextString(m) }
func (*ListContactFilter) ProtoMessage()    {}
func (*ListContactFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{2}
}

func (m *ListContactFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactFilter.Unmarshal(m, b)
}
func (m *ListContactFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactFilter.Marshal(b, m, deterministic)
}
func (m *ListContactFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactFilter.Merge(m, src)
}
func (m *ListContactFilter) XXX_Size() int {
	return xxx_messageInfo_ListContactFilter.Size(m)
}
func (m *ListContactFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactFilter proto.InternalMessageInfo

func (m *ListContactFilter) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ListContactFilter) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *ListContactFilter) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

type ListContactsResponse struct {
	// контакты
	Contacts             []*Contact `protobuf:"bytes,1,rep,name=contacts,proto3" json:"contacts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListContactsResponse) Reset()         { *m = ListContactsResponse{} }
func (m *ListContactsResponse) String() string { return proto.CompactTextString(m) }
func (*ListContactsResponse) ProtoMessage()    {}
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{3}
}

func (m *ListContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsResponse.Unmarshal(m, b)
}
func (m *ListContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsResponse.Marshal(b, m, deterministic)
}
func (m *ListContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsResponse.Merge(m, src)
}
func (m *ListContactsResponse) XXX_Size() int {
	return xxx_messageInfo_ListContactsResponse.Size(m)
}
func (m *ListContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsResponse proto.InternalMessageInfo

func (m *ListContactsResponse) GetContacts() []*Contact {
	if m != nil {
		return m.Contacts
	}
	return nil
}

type AddContactRequest struct {
	// имя
	Name *wrappers.StringValue `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// телефон
	Phone                *wrappers.StringValue `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *AddContactRequest) Reset()         { *m = AddContactRequest{} }
func (m *AddContactRequest) String() string { return proto.CompactTextString(m) }
func (*AddContactRequest) ProtoMessage()    {}
func (*AddContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{4}
}

func (m *AddContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AddContactRequest.Unmarshal(m, b)
}
func (m *AddContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AddContactRequest.Marshal(b, m, deterministic)
}
func (m *AddContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AddContactRequest.Merge(m, src)
}
func (m *AddContactRequest) XXX_Size() int {
	return xxx_messageInfo_AddContactRequest.Size(m)
}
func (m *AddContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AddContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AddContactRequest proto.InternalMessageInfo

func (m *AddContactRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *AddContactRequest) GetPhone() *wrappers.StringValue {
	if m != nil {
		return m.Phone
	}
	return nil
}

type IsErr struct {
	// ошибка(если возникла)
	Err                  *wrappers.StringValue `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *IsErr) Reset()         { *m = IsErr{} }
func (m *IsErr) String() string { return proto.CompactTextString(m) }
func (*IsErr) ProtoMessage()    {}
func (*IsErr) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{5}
}

func (m *IsErr) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_IsErr.Unmarshal(m, b)
}
func (m *IsErr) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_IsErr.Marshal(b, m, deterministic)
}
func (m *IsErr) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IsErr.Merge(m, src)
}
func (m *IsErr) XXX_Size() int {
	return xxx_messageInfo_IsErr.Size(m)
}
func (m *IsErr) XXX_DiscardUnknown() {
	xxx_messageInfo_IsErr.DiscardUnknown(m)
}

var xxx_messageInfo_IsErr proto.InternalMessageInfo

func (m *IsErr) GetErr() *wrappers.StringValue {
	if m != nil {
		return m.Err
	}
	return nil
}

type UpdateContactRequest struct {
	// id записи
	Id *wrappers.Int64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// имя
	Name *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// телефон
	Phone                *wrappers.StringValue `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateContactRequest) Reset()         { *m = UpdateContactRequest{} }
func (m *UpdateContactRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateContactRequest) ProtoMessage()    {}
func (*UpdateContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{6}
}

func (m *UpdateContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateContactRequest.Unmarshal(m, b)
}
func (m *UpdateContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateContactRequest.Marshal(b, m, deterministic)
}
func (m *UpdateContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateContactRequest.Merge(m, src)
}
func (m *UpdateContactRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateContactRequest.Size(m)
}
func (m *UpdateContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateContactRequest proto.InternalMessageInfo

func (m *UpdateContactRequest) GetId() *wrappers.Int64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *UpdateContactRequest) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *UpdateContactRequest) GetPhone() *wrappers.StringValue {
	if m != nil {
		return m.Phone
	}
	return nil
}

type DeleteContactRequest struct {
	// id записи
	Id                   *wrappers.Int64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteContactRequest) Reset()         { *m = DeleteContactRequest{} }
func (m *DeleteContactRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteContactRequest) ProtoMessage()    {}
func (*DeleteContactRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{7}
}

func (m *DeleteContactRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteContactRequest.Unmarshal(m, b)
}
func (m *DeleteContactRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteContactRequest.Marshal(b, m, deterministic)
}
func (m *DeleteContactRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteContactRequest.Merge(m, src)
}
func (m *DeleteContactRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteContactRequest.Size(m)
}
func (m *DeleteContactRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteContactRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteContactRequest proto.InternalMessageInfo

func (m *DeleteContactRequest) GetId() *wrappers.Int64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.crud.ContactFieldNum", ContactFieldNum_name, ContactFieldNum_value)
	proto.RegisterType((*Contact)(nil), "api.crud.Contact")
	proto.RegisterType((*ListContactsRequest)(nil), "api.crud.ListContactsRequest")
	proto.RegisterType((*ListContactFilter)(nil), "api.crud.ListContactFilter")
	proto.RegisterType((*ListContactsResponse)(nil), "api.crud.ListContactsResponse")
	proto.RegisterType((*AddContactRequest)(nil), "api.crud.AddContactRequest")
	proto.RegisterType((*IsErr)(nil), "api.crud.IsErr")
	proto.RegisterType((*UpdateContactRequest)(nil), "api.crud.UpdateContactRequest")
	proto.RegisterType((*DeleteContactRequest)(nil), "api.crud.DeleteContactRequest")
}

func init() {
	proto.RegisterFile("phonebook.proto", fileDescriptor_34db5399df65ad55)
}

var fileDescriptor_34db5399df65ad55 = []byte{
	// 503 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x92, 0xdf, 0x8e, 0xd2, 0x40,
	0x14, 0xc6, 0x9d, 0x16, 0xba, 0x78, 0x48, 0x76, 0x61, 0x24, 0xa6, 0xae, 0x46, 0x49, 0xaf, 0x88,
	0x86, 0xa2, 0xb0, 0x59, 0x8d, 0x77, 0x0b, 0xcb, 0x46, 0xa2, 0xa2, 0xe9, 0x46, 0x2f, 0xbc, 0x21,
	0x85, 0x99, 0xed, 0x4e, 0xb6, 0xed, 0xd4, 0x99, 0xa9, 0x3c, 0x83, 0xef, 0xe0, 0x4b, 0xf8, 0x0e,
	0xbe, 0x87, 0x89, 0x4f, 0x62, 0x98, 0x0e, 0x55, 0xc1, 0x44, 0x4c, 0x8c, 0x77, 0xf3, 0xe7, 0xf7,
	0xcd, 0x7c, 0xe7, 0x3b, 0x07, 0x0e, 0xb2, 0x4b, 0x9e, 0xd2, 0x39, 0xe7, 0x57, 0x7e, 0x26, 0xb8,
	0xe2, 0xb8, 0x16, 0x66, 0xcc, 0x5f, 0x88, 0x9c, 0x1c, 0xde, 0x8d, 0x38, 0x8f, 0x62, 0xda, 0xd3,
	0xe7, 0xf3, 0xfc, 0xa2, 0xb7, 0x14, 0x61, 0x96, 0x51, 0x21, 0x0b, 0xf2, 0xf0, 0x38, 0x62, 0xea,
	0x32, 0x9f, 0xfb, 0x0b, 0x9e, 0xf4, 0x92, 0x25, 0x53, 0x57, 0x7c, 0xd9, 0x8b, 0x78, 0x57, 0x5f,
	0x76, 0x3f, 0x84, 0x31, 0x23, 0xa1, 0xe2, 0x42, 0xf6, 0xca, 0x65, 0xa1, 0xf3, 0x3e, 0x21, 0xd8,
	0x1b, 0xf1, 0x54, 0x85, 0x0b, 0x85, 0x1f, 0x80, 0xc5, 0x88, 0x8b, 0xda, 0xa8, 0x53, 0xef, 0xdf,
	0xf6, 0x8b, 0x0f, 0xfd, 0xf5, 0x87, 0xfe, 0x24, 0x55, 0xc7, 0x47, 0x6f, 0xc3, 0x38, 0xa7, 0x81,
	0xc5, 0x08, 0x7e, 0x08, 0x95, 0x34, 0x4c, 0xa8, 0x6b, 0x69, 0xfc, 0xce, 0x16, 0x7e, 0xae, 0x04,
	0x4b, 0xa3, 0x82, 0xd7, 0x24, 0xee, 0x43, 0x55, 0xd7, 0xe7, 0xda, 0x3b, 0x48, 0x0a, 0xd4, 0xfb,
	0x82, 0xe0, 0xc6, 0x0b, 0x26, 0x95, 0xb1, 0x28, 0x03, 0xfa, 0x3e, 0xa7, 0x52, 0xe1, 0x01, 0x38,
	0x17, 0x2c, 0x56, 0x54, 0x94, 0x76, 0xd7, 0x49, 0xf9, 0x3f, 0xe1, 0x67, 0x1a, 0x09, 0x0c, 0x8a,
	0xc7, 0xb0, 0x2f, 0xa8, 0xca, 0x45, 0x4a, 0xc9, 0x19, 0xa3, 0x31, 0x91, 0xae, 0xd5, 0xb6, 0x3b,
	0xfb, 0xfd, 0x5b, 0x3f, 0xc4, 0xa5, 0x90, 0xc6, 0x64, 0x9a, 0x27, 0x43, 0xcb, 0x45, 0xc1, 0x86,
	0x08, 0x3f, 0x82, 0x6a, 0xcc, 0x12, 0xa6, 0x4c, 0x1d, 0xbf, 0x4d, 0x6a, 0xd0, 0x37, 0x65, 0x68,
	0xd2, 0x3b, 0x87, 0xe6, 0x96, 0x2d, 0xdc, 0x00, 0x9b, 0x11, 0xe9, 0xa2, 0xb6, 0xdd, 0xb1, 0x83,
	0xd5, 0x12, 0xb7, 0xa0, 0xba, 0x4a, 0xaa, 0xf0, 0x75, 0x3d, 0x28, 0x36, 0xf8, 0x26, 0x38, 0x3a,
	0x0c, 0xe9, 0xda, 0xfa, 0xd8, 0xec, 0xbc, 0x31, 0xb4, 0x7e, 0x8d, 0x46, 0x66, 0x3c, 0x95, 0x14,
	0x77, 0xa1, 0xb6, 0x30, 0x67, 0xfa, 0xf1, 0x7a, 0xbf, 0xb9, 0x55, 0x60, 0x50, 0x22, 0xde, 0x47,
	0x04, 0xcd, 0x13, 0x42, 0xd6, 0x17, 0x26, 0xe0, 0x27, 0xa6, 0xbd, 0xe8, 0xcf, 0xbd, 0x1a, 0x3a,
	0xdf, 0xbe, 0xde, 0xb3, 0xda, 0xc8, 0xb4, 0xf9, 0xe9, 0xba, 0xcd, 0xd6, 0x5f, 0x48, 0x4d, 0xbb,
	0x1f, 0x43, 0x75, 0x22, 0xc7, 0x42, 0x60, 0x1f, 0x6c, 0x2a, 0xc4, 0x2e, 0xbf, 0x07, 0x2b, 0xd0,
	0xfb, 0x8c, 0xa0, 0xf5, 0x26, 0x23, 0xa1, 0xa2, 0x1b, 0x75, 0x0c, 0x76, 0x9c, 0xe9, 0xd2, 0xc9,
	0xff, 0x9b, 0xed, 0xe7, 0xd0, 0x3a, 0xa5, 0x31, 0xfd, 0x27, 0x96, 0xef, 0x1f, 0xc1, 0xc1, 0xc6,
	0xec, 0xe2, 0x1a, 0x54, 0x46, 0xb3, 0xc9, 0x69, 0xe3, 0x1a, 0x06, 0x70, 0x46, 0xb3, 0xe9, 0xc9,
	0xcb, 0x71, 0x03, 0xe1, 0x3a, 0xec, 0x8d, 0x66, 0xaf, 0x9f, 0xbd, 0x9a, 0x8e, 0x1b, 0xd6, 0xd0,
	0x79, 0x57, 0x59, 0x4d, 0xc5, 0xdc, 0xd1, 0xcf, 0x0f, 0xbe, 0x07, 0x00, 0x00, 0xff, 0xff, 0x7a,
	0x8e, 0xdf, 0xbf, 0x81, 0x04, 0x00, 0x00,
}
