// Code generated by protoc-gen-go. DO NOT EDIT.
// source: phonebook.proto

package crud

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type ContactFieldNum int32

const (
	ContactFieldNum_C_ID    ContactFieldNum = 0
	ContactFieldNum_C_NAME  ContactFieldNum = 1
	ContactFieldNum_C_PHONE ContactFieldNum = 2
)

var ContactFieldNum_name = map[int32]string{
	0: "C_ID",
	1: "C_NAME",
	2: "C_PHONE",
}

var ContactFieldNum_value = map[string]int32{
	"C_ID":    0,
	"C_NAME":  1,
	"C_PHONE": 2,
}

func (x ContactFieldNum) String() string {
	return proto.EnumName(ContactFieldNum_name, int32(x))
}

func (ContactFieldNum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{0}
}

type Contact struct {
	// id записи
	Id *wrappers.Int64Value `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// имя
	Name *wrappers.StringValue `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// телефон
	Phone                *wrappers.StringValue `protobuf:"bytes,3,opt,name=phone,proto3" json:"phone,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *Contact) Reset()         { *m = Contact{} }
func (m *Contact) String() string { return proto.CompactTextString(m) }
func (*Contact) ProtoMessage()    {}
func (*Contact) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{0}
}

func (m *Contact) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Contact.Unmarshal(m, b)
}
func (m *Contact) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Contact.Marshal(b, m, deterministic)
}
func (m *Contact) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Contact.Merge(m, src)
}
func (m *Contact) XXX_Size() int {
	return xxx_messageInfo_Contact.Size(m)
}
func (m *Contact) XXX_DiscardUnknown() {
	xxx_messageInfo_Contact.DiscardUnknown(m)
}

var xxx_messageInfo_Contact proto.InternalMessageInfo

func (m *Contact) GetId() *wrappers.Int64Value {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Contact) GetName() *wrappers.StringValue {
	if m != nil {
		return m.Name
	}
	return nil
}

func (m *Contact) GetPhone() *wrappers.StringValue {
	if m != nil {
		return m.Phone
	}
	return nil
}

type ListContactsRequest struct {
	// фильтры для отбора записей
	Filter *ListCityFilter `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	// список названий полей, которые возвращать в ответе (при отсутствии возвращаем все параметры)
	ReturnedFields []ContactFieldNum `protobuf:"varint,2,rep,packed,name=returnedFields,proto3,enum=api.crud.ContactFieldNum" json:"returnedFields,omitempty"`
	// ограничение числа возвращаемых записей
	Limit                *wrappers.Int32Value `protobuf:"bytes,3,opt,name=limit,proto3" json:"limit,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *ListContactsRequest) Reset()         { *m = ListContactsRequest{} }
func (m *ListContactsRequest) String() string { return proto.CompactTextString(m) }
func (*ListContactsRequest) ProtoMessage()    {}
func (*ListContactsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{1}
}

func (m *ListContactsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsRequest.Unmarshal(m, b)
}
func (m *ListContactsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsRequest.Marshal(b, m, deterministic)
}
func (m *ListContactsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsRequest.Merge(m, src)
}
func (m *ListContactsRequest) XXX_Size() int {
	return xxx_messageInfo_ListContactsRequest.Size(m)
}
func (m *ListContactsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsRequest proto.InternalMessageInfo

func (m *ListContactsRequest) GetFilter() *ListCityFilter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListContactsRequest) GetReturnedFields() []ContactFieldNum {
	if m != nil {
		return m.ReturnedFields
	}
	return nil
}

func (m *ListContactsRequest) GetLimit() *wrappers.Int32Value {
	if m != nil {
		return m.Limit
	}
	return nil
}

type ListCityFilter struct {
	// список id
	Ids []int64 `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	// список имен
	Names []string `protobuf:"bytes,2,rep,name=names,proto3" json:"names,omitempty"`
	// список телефонов
	Phones               []string `protobuf:"bytes,3,rep,name=phones,proto3" json:"phones,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListCityFilter) Reset()         { *m = ListCityFilter{} }
func (m *ListCityFilter) String() string { return proto.CompactTextString(m) }
func (*ListCityFilter) ProtoMessage()    {}
func (*ListCityFilter) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{2}
}

func (m *ListCityFilter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListCityFilter.Unmarshal(m, b)
}
func (m *ListCityFilter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListCityFilter.Marshal(b, m, deterministic)
}
func (m *ListCityFilter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListCityFilter.Merge(m, src)
}
func (m *ListCityFilter) XXX_Size() int {
	return xxx_messageInfo_ListCityFilter.Size(m)
}
func (m *ListCityFilter) XXX_DiscardUnknown() {
	xxx_messageInfo_ListCityFilter.DiscardUnknown(m)
}

var xxx_messageInfo_ListCityFilter proto.InternalMessageInfo

func (m *ListCityFilter) GetIds() []int64 {
	if m != nil {
		return m.Ids
	}
	return nil
}

func (m *ListCityFilter) GetNames() []string {
	if m != nil {
		return m.Names
	}
	return nil
}

func (m *ListCityFilter) GetPhones() []string {
	if m != nil {
		return m.Phones
	}
	return nil
}

type ListContactsResponse struct {
	// контакты
	Cities               []*Contact `protobuf:"bytes,1,rep,name=cities,proto3" json:"cities,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListContactsResponse) Reset()         { *m = ListContactsResponse{} }
func (m *ListContactsResponse) String() string { return proto.CompactTextString(m) }
func (*ListContactsResponse) ProtoMessage()    {}
func (*ListContactsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_34db5399df65ad55, []int{3}
}

func (m *ListContactsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListContactsResponse.Unmarshal(m, b)
}
func (m *ListContactsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListContactsResponse.Marshal(b, m, deterministic)
}
func (m *ListContactsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListContactsResponse.Merge(m, src)
}
func (m *ListContactsResponse) XXX_Size() int {
	return xxx_messageInfo_ListContactsResponse.Size(m)
}
func (m *ListContactsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListContactsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListContactsResponse proto.InternalMessageInfo

func (m *ListContactsResponse) GetCities() []*Contact {
	if m != nil {
		return m.Cities
	}
	return nil
}

func init() {
	proto.RegisterEnum("api.crud.ContactFieldNum", ContactFieldNum_name, ContactFieldNum_value)
	proto.RegisterType((*Contact)(nil), "api.crud.Contact")
	proto.RegisterType((*ListContactsRequest)(nil), "api.crud.ListContactsRequest")
	proto.RegisterType((*ListCityFilter)(nil), "api.crud.ListCityFilter")
	proto.RegisterType((*ListContactsResponse)(nil), "api.crud.ListContactsResponse")
}

func init() {
	proto.RegisterFile("phonebook.proto", fileDescriptor_34db5399df65ad55)
}

var fileDescriptor_34db5399df65ad55 = []byte{
	// 376 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x90, 0xcf, 0x4e, 0xf2, 0x40,
	0x14, 0xc5, 0xbf, 0xb6, 0x50, 0xf8, 0x2e, 0x09, 0xd4, 0x91, 0x98, 0xfa, 0x27, 0x86, 0x74, 0x85,
	0x9a, 0x14, 0x2c, 0xc4, 0x3d, 0x56, 0x88, 0x24, 0x8a, 0xa4, 0x26, 0x2e, 0xdc, 0x90, 0x42, 0x07,
	0x9c, 0x58, 0x3a, 0x75, 0x66, 0x1a, 0xe3, 0xbb, 0xf8, 0x2a, 0xbe, 0x9b, 0x61, 0x3a, 0xc4, 0x00,
	0x2e, 0xdc, 0x75, 0xee, 0xfd, 0x9d, 0xdb, 0x73, 0x0e, 0xd4, 0xd2, 0x17, 0x9a, 0xe0, 0x29, 0xa5,
	0xaf, 0x6e, 0xca, 0xa8, 0xa0, 0xa8, 0x1c, 0xa6, 0xc4, 0x9d, 0xb1, 0x2c, 0x3a, 0x3a, 0x5d, 0x50,
	0xba, 0x88, 0x71, 0x4b, 0xce, 0xa7, 0xd9, 0xbc, 0xf5, 0xce, 0xc2, 0x34, 0xc5, 0x8c, 0xe7, 0xa4,
	0xf3, 0xa9, 0x41, 0xc9, 0xa7, 0x89, 0x08, 0x67, 0x02, 0x5d, 0x80, 0x4e, 0x22, 0x5b, 0x6b, 0x68,
	0xcd, 0x8a, 0x77, 0xec, 0xe6, 0x42, 0x77, 0x2d, 0x74, 0x87, 0x89, 0xb8, 0xea, 0x3e, 0x85, 0x71,
	0x86, 0x03, 0x9d, 0x44, 0xa8, 0x0d, 0x85, 0x24, 0x5c, 0x62, 0x5b, 0x97, 0xf8, 0xc9, 0x0e, 0xfe,
	0x28, 0x18, 0x49, 0x16, 0x39, 0x2f, 0x49, 0xe4, 0x41, 0x51, 0xfa, 0xb4, 0x8d, 0x3f, 0x48, 0x72,
	0xd4, 0xf9, 0xd2, 0x60, 0xff, 0x8e, 0x70, 0xa1, 0x2c, 0xf2, 0x00, 0xbf, 0x65, 0x98, 0x0b, 0xd4,
	0x06, 0x73, 0x4e, 0x62, 0x81, 0x99, 0xb2, 0x6b, 0xbb, 0xeb, 0xc4, 0xae, 0xc4, 0x89, 0xf8, 0x18,
	0xc8, 0x7d, 0xa0, 0x38, 0xd4, 0x83, 0x2a, 0xc3, 0x22, 0x63, 0x09, 0x8e, 0x06, 0x04, 0xc7, 0x11,
	0xb7, 0xf5, 0x86, 0xd1, 0xac, 0x7a, 0x87, 0x3f, 0x4a, 0xf5, 0x13, 0xb9, 0x1e, 0x65, 0xcb, 0x60,
	0x4b, 0x80, 0x2e, 0xa1, 0x18, 0x93, 0x25, 0x11, 0x2a, 0xc0, 0xaf, 0x15, 0x75, 0x3c, 0xe5, 0x5f,
	0x92, 0xce, 0x18, 0xaa, 0x9b, 0x7e, 0x90, 0x05, 0x06, 0x89, 0xb8, 0xad, 0x35, 0x8c, 0xa6, 0x11,
	0xac, 0x3e, 0x51, 0x1d, 0x8a, 0xab, 0x7e, 0x72, 0x43, 0xff, 0x83, 0xfc, 0x81, 0x0e, 0xc0, 0x94,
	0x15, 0x70, 0xdb, 0x90, 0x63, 0xf5, 0x72, 0x7a, 0x50, 0xdf, 0x2c, 0x84, 0xa7, 0x34, 0xe1, 0x18,
	0x9d, 0x81, 0x39, 0x23, 0x82, 0xe0, 0xfc, 0x74, 0xc5, 0xdb, 0xdb, 0xc9, 0x15, 0x28, 0xe0, 0xbc,
	0x0b, 0xb5, 0xad, 0xa8, 0xa8, 0x0c, 0x05, 0x7f, 0x32, 0xbc, 0xb1, 0xfe, 0x21, 0x00, 0xd3, 0x9f,
	0x8c, 0x7a, 0xf7, 0x7d, 0x4b, 0x43, 0x15, 0x28, 0xf9, 0x93, 0xf1, 0xed, 0xc3, 0xa8, 0x6f, 0xe9,
	0xd7, 0xe6, 0x73, 0x61, 0x75, 0x6d, 0x6a, 0xca, 0xb8, 0x9d, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x58, 0x75, 0x25, 0x9e, 0x75, 0x02, 0x00, 0x00,
}
