// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package crud

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

func init() {
	proto.RegisterFile("service.proto", fileDescriptor_a0b84a42fa06f626)
}

var fileDescriptor_a0b84a42fa06f626 = []byte{
	// 270 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xcd, 0x4a, 0xc3, 0x40,
	0x14, 0x85, 0xa9, 0x88, 0x84, 0x58, 0x51, 0x06, 0xdc, 0x04, 0x95, 0xe2, 0xda, 0x66, 0xf0, 0xe7,
	0x05, 0x6a, 0xb6, 0xae, 0x5c, 0xba, 0x10, 0xa6, 0x71, 0x18, 0x07, 0xc3, 0xdc, 0x31, 0x77, 0x5a,
	0xb7, 0x36, 0x3b, 0xb7, 0xf1, 0x39, 0x84, 0x50, 0x10, 0x25, 0x68, 0x7c, 0x85, 0x3b, 0xf8, 0x0a,
	0x3e, 0x88, 0x98, 0xa0, 0x74, 0x61, 0x57, 0x17, 0xbe, 0xf3, 0x71, 0x39, 0x27, 0xdc, 0x40, 0x99,
	0x4f, 0x75, 0x2a, 0x63, 0x9b, 0x83, 0x03, 0x16, 0x08, 0xab, 0xe3, 0x34, 0x9f, 0x5c, 0x45, 0x3b,
	0x0a, 0x40, 0x65, 0x92, 0x0b, 0xab, 0xb9, 0x30, 0x06, 0x9c, 0x70, 0x1a, 0x0c, 0x76, 0x5e, 0x74,
	0xd0, 0x9e, 0x74, 0xa8, 0xa4, 0x19, 0xe2, 0x9d, 0x50, 0x4a, 0xe6, 0x1c, 0x6c, 0x6b, 0xfc, 0x63,
	0x6f, 0xda, 0x6b, 0x30, 0x72, 0x0c, 0x70, 0xd3, 0x81, 0xa3, 0xba, 0x17, 0x06, 0x09, 0x18, 0x27,
	0x52, 0x87, 0xec, 0xa9, 0x17, 0xf6, 0xcf, 0x34, 0xba, 0x3f, 0xb0, 0x1b, 0xff, 0xb6, 0x88, 0x17,
	0xf9, 0xb9, 0xbc, 0x9d, 0x48, 0x74, 0xd1, 0xde, 0xb2, 0x18, 0x2d, 0x18, 0x94, 0xfb, 0x97, 0xe5,
	0x28, 0x61, 0xeb, 0x0b, 0x51, 0x74, 0x42, 0x25, 0x35, 0xf4, 0x42, 0x73, 0x7f, 0x4f, 0x95, 0x7f,
	0xa0, 0x8a, 0x9e, 0xe9, 0x6d, 0xe0, 0x67, 0xf4, 0x41, 0xaf, 0x7e, 0x46, 0x0d, 0xd5, 0x03, 0xaa,
	0xa9, 0xa1, 0x77, 0x5f, 0x50, 0x45, 0xb5, 0x2f, 0xa8, 0xa1, 0x79, 0xf1, 0xf9, 0xf5, 0xb8, 0xc2,
	0xd8, 0x16, 0x9f, 0x1e, 0xf2, 0xb4, 0x7b, 0xc4, 0x33, 0x8d, 0xee, 0x74, 0xbb, 0x1c, 0xf5, 0x59,
	0x18, 0x06, 0x89, 0x70, 0x22, 0x03, 0x85, 0x17, 0xab, 0x3f, 0x5d, 0xc6, 0x6b, 0xed, 0xb4, 0xe3,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x33, 0xdf, 0x6d, 0x48, 0x52, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// ContactsClient is the client API for Contacts service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ContactsClient interface {
	ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error)
}

type contactsClient struct {
	cc grpc.ClientConnInterface
}

func NewContactsClient(cc grpc.ClientConnInterface) ContactsClient {
	return &contactsClient{cc}
}

func (c *contactsClient) ListContacts(ctx context.Context, in *ListContactsRequest, opts ...grpc.CallOption) (*ListContactsResponse, error) {
	out := new(ListContactsResponse)
	err := c.cc.Invoke(ctx, "/api.crud.Contacts/ListContacts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ContactsServer is the server API for Contacts service.
type ContactsServer interface {
	ListContacts(context.Context, *ListContactsRequest) (*ListContactsResponse, error)
}

// UnimplementedContactsServer can be embedded to have forward compatible implementations.
type UnimplementedContactsServer struct {
}

func (*UnimplementedContactsServer) ListContacts(ctx context.Context, req *ListContactsRequest) (*ListContactsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListContacts not implemented")
}

func RegisterContactsServer(s *grpc.Server, srv ContactsServer) {
	s.RegisterService(&_Contacts_serviceDesc, srv)
}

func _Contacts_ListContacts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListContactsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ContactsServer).ListContacts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.crud.Contacts/ListContacts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ContactsServer).ListContacts(ctx, req.(*ListContactsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Contacts_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.crud.Contacts",
	HandlerType: (*ContactsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListContacts",
			Handler:    _Contacts_ListContacts_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
